# Form implementation generated from reading ui file 'signinUI.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 576)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(331, 480))
        self.groupBox.setMaximumSize(QtCore.QSize(331, 480))
        self.groupBox.setStyleSheet("QGroupBox#groupBox {\n"
"    background-color: #7f7f7f; /* White background */\n"
"    background-color: rgb(213, 213, 213);\n"
"    border-radius: 15px; /* Smooth rounded corners */\n"
"    border: 1px solid #e6e6e6; /* Subtle border */\n"
"    box-shadow: 0px 4px 15px rgba(0, 0, 0, 0.25); /* Shadow effect */\n"
"    margin-top: 10px; /* Space above the title (if there’s a title) */\n"
"}\n"
"\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.loginWid = QtWidgets.QWidget(parent=self.groupBox)
        self.loginWid.setMinimumSize(QtCore.QSize(311, 141))
        self.loginWid.setObjectName("loginWid")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.loginWid)
        self.verticalLayout.setObjectName("verticalLayout")
        self.loginLeb = QtWidgets.QLabel(parent=self.loginWid)
        self.loginLeb.setStyleSheet("font: 9pt \"Segoe Script\";")
        self.loginLeb.setObjectName("loginLeb")
        self.verticalLayout.addWidget(self.loginLeb)
        self.loginMsg = QtWidgets.QLabel(parent=self.loginWid)
        self.loginMsg.setStyleSheet("font: 12pt \"Kristen ITC\";")
        self.loginMsg.setObjectName("loginMsg")
        self.verticalLayout.addWidget(self.loginMsg)
        self.verticalLayout_2.addWidget(self.loginWid)
        self.inputFieldWid = QtWidgets.QWidget(parent=self.groupBox)
        self.inputFieldWid.setMinimumSize(QtCore.QSize(311, 121))
        self.inputFieldWid.setObjectName("inputFieldWid")
        self.gridLayout = QtWidgets.QGridLayout(self.inputFieldWid)
        self.gridLayout.setObjectName("gridLayout")
        self.passwordField = QtWidgets.QLineEdit(parent=self.inputFieldWid)
        self.passwordField.setMinimumSize(QtCore.QSize(261, 39))
        self.passwordField.setStyleSheet("QLineEdit {\n"
"    background-color: #f5f5f5; /* Light gray background */\n"
"    border: 1px solid #dcdcdc; /* Subtle border */\n"
"    border-radius: 15px; /* Rounded corners */\n"
"    padding: 8px; /* Spacing inside the input box */\n"
"    font-size: 14px; /* Adjust font size */\n"
"    color: #333; /* Text color */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #fbbd42; /* Highlighted border when focused */\n"
"    outline: none; /* Remove the default outline */\n"
"}\n"
"QLineEdit::placeholder {\n"
"    color: #aaa; /* Light gray for placeholder */\n"
"}\n"
"")
        self.passwordField.setInputMask("")
        self.passwordField.setText("")
        self.passwordField.setMaxLength(100)
        self.passwordField.setObjectName("passwordField")
        self.gridLayout.addWidget(self.passwordField, 1, 0, 1, 1)
        self.eyeButton = QtWidgets.QToolButton(parent=self.inputFieldWid)
        self.eyeButton.setIconSize(QtCore.QSize(20, 20))
        self.eyeButton.setObjectName("eyeButton")
        self.gridLayout.addWidget(self.eyeButton, 1, 1, 1, 1)
        self.usernameField = QtWidgets.QLineEdit(parent=self.inputFieldWid)
        self.usernameField.setMinimumSize(QtCore.QSize(261, 39))
        self.usernameField.setStyleSheet("QLineEdit {\n"
"    background-color: #f5f5f5; /* Light gray background */\n"
"    border: 1px solid #dcdcdc; /* Subtle border */\n"
"    border-radius: 15px; /* Rounded corners */\n"
"    padding: 8px; /* Spacing inside the input box */\n"
"    font-size: 14px; /* Adjust font size */\n"
"    color: #333; /* Text color */\n"
"    box-shadow: 0px 4px 20px rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #fbbd42; /* Highlighted border when focused */\n"
"    outline: none; /* Remove the default outline */\n"
"}\n"
"QLineEdit::placeholder {\n"
"    color: #aaa; /* Light gray for placeholder */\n"
"}\n"
"")
        self.usernameField.setInputMask("")
        self.usernameField.setText("")
        self.usernameField.setMaxLength(100)
        self.usernameField.setObjectName("usernameField")
        self.gridLayout.addWidget(self.usernameField, 0, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.inputFieldWid)
        self.statLeb = QtWidgets.QLabel(parent=self.groupBox)
        self.statLeb.setStyleSheet("color: red;\n"
"font-weight: bold;")
        self.statLeb.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.statLeb.setObjectName("statLeb")
        self.verticalLayout_2.addWidget(self.statLeb)
        self.signInWid = QtWidgets.QWidget(parent=self.groupBox)
        self.signInWid.setMinimumSize(QtCore.QSize(311, 69))
        self.signInWid.setObjectName("signInWid")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.signInWid)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.signinButton = QtWidgets.QPushButton(parent=self.signInWid)
        self.signinButton.setMinimumSize(QtCore.QSize(111, 51))
        self.signinButton.setMaximumSize(QtCore.QSize(111, 51))
        self.signinButton.setStyleSheet("QPushButton {\n"
"    background-color: #050505; /* Default background color */\n"
"    color: #fafafa; /* Text color */\n"
"    border: 2px solid; /* Remove border */\n"
"    border-radius: 20px; /* Rounded corners */\n"
"    padding: 5px 10px; /* Padding for the button */\n"
"    font: 10pt \"Roboto\";  /* Font style */\n"
"    box-shadow: none; /* No shadow by default */\n"
"    transition: all 0.3s ease; /* Smooth transition for hover effects */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff9f00; /* Change background color on hover */\n"
"    box-shadow: 0px 4px 15px rgba(0, 0, 0, 0.25); /* Add shadow on hover */\n"
"    color: #ffffff; /* Keep text color the same */\n"
"}\n"
"")
        self.signinButton.setObjectName("signinButton")
        self.gridLayout_2.addWidget(self.signinButton, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.signInWid)
        self.linkWid = QtWidgets.QWidget(parent=self.groupBox)
        self.linkWid.setMinimumSize(QtCore.QSize(311, 58))
        self.linkWid.setObjectName("linkWid")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.linkWid)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dntHaveAnAcc = QtWidgets.QLabel(parent=self.linkWid)
        self.dntHaveAnAcc.setMinimumSize(QtCore.QSize(151, 0))
        self.dntHaveAnAcc.setStyleSheet("font: 10pt \"Roboto\";\n"
"text-align: center; /* Horizontal alignment */\n"
"qproperty-alignment: \'AlignVCenter\'; /* Vertical alignment */\n"
"padding: 3px;\n"
"")
        self.dntHaveAnAcc.setObjectName("dntHaveAnAcc")
        self.horizontalLayout.addWidget(self.dntHaveAnAcc)
        self.regHereButton = QtWidgets.QCommandLinkButton(parent=self.linkWid)
        self.regHereButton.setStyleSheet("font: 10pt \"Roboto\";\n"
"text-align: center;\n"
"")
        self.regHereButton.setObjectName("regHereButton")
        self.horizontalLayout.addWidget(self.regHereButton, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_2.addWidget(self.linkWid)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loginLeb.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\"font-size:18pt; font-weight:700;\">Login</span></p></body></html>"))
        self.loginMsg.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Hey! Enter you details to get </p><p align=\"center\">signed in to your account.</p></body></html>"))
        self.passwordField.setPlaceholderText(_translate("MainWindow", "Password"))
        self.eyeButton.setText(_translate("MainWindow", "👁"))
        self.usernameField.setPlaceholderText(_translate("MainWindow", "Username"))
        self.statLeb.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.signinButton.setText(_translate("MainWindow", "Sign in"))
        self.dntHaveAnAcc.setText(_translate("MainWindow", "<html><head/><body><p>Don\'t have any account?</p></body></html>"))
        self.regHereButton.setText(_translate("MainWindow", "Register here"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
